version: '2'
services:
  isubank:
    image: golang:1.10
    command: bash -c "go get ./... && go run main.go -port=5515 -dbhost=mysql -dbuser=root -dbpass=root"
    ports:
      - "5515:5515"
    links:
      - mysql
    working_dir: /go/src/bank
    volumes:
      - isubankgopath:/go
      - ./bank:/go/src/bank

  logger:
    image: golang:1.10
    command: bash -c "go get ./... && go run main.go -port=5516 -dbhost=mysql -dbuser=root -dbpass=root"
    ports:
      - "5516:5516"
    links:
      - mysql
    working_dir: /go/src/logger
    volumes:
      - loggergopath:/go
      - ./logger:/go/src/logger

  mysql:
    image: mysql:8
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  isubankgopath:
  loggergopath:
  mysql:
